export const __VLG_IMPORT_PROPERTY_DECORATOR__ =
  "__VLG_IMPORT_PROPERTY_DECORATOR__";

export const __VLG_IMPORT_PRIMITIVE_PROPERTY_DECORATOR__ =
  "__VLG_IMPORT_PRIMITIVE_PROPERTY_DECORATOR__";

export const __VLG_TRANSFORM_DECORATOR__ = "__VLG_TRANSFORM_DECORATOR__";
